import { useEffect, useMemo, useRef, useState, type RefObject } from 'react'

type Lugar = { _id: string; nombre: string; alias?: string[]; zona: string; ubicacion?: string }
type Seleccion = Lugar | null
type Cotizacion = { encontrado: boolean; motivo?: string; van?: number; sprinter?: number; cargos?: Array<{ concepto: string; monto: number }>; notas?: string[]; vigencia?: string; nombreTabla?: string; detalleOrigen?: { nombre?: string; zona?: string }; detalleDestino?: { nombre?: string; zona?: string } }
type Tour = { salida: string; items: Array<{ nombre: string; van?: number; sprinter?: number }> }
type Extra = { nombre: string; van?: number; sprinter?: number }
type Zona = { clave: string; nombre: string }

const QUICK_PLACES: Lugar[] = [
  { _id: 'aeropuerto_cun', nombre: 'Aeropuerto Cancún', zona: 'aeropuerto_cun' },
  { _id: 'aeropuerto_tqo', nombre: 'Aeropuerto Tulum', zona: 'aeropuerto_tqo' },
  { _id: 'cancun_centro', nombre: 'Cancún Centro', zona: 'cancun_centro' },
  { _id: 'playa_centro', nombre: 'Playa Centro', zona: 'playa_centro' },
  { _id: 'tulum_centro', nombre: 'Tulum Centro', zona: 'tulum_centro' },
]
const networkMessage = 'No hay conexión. Revisa tu internet e inténtalo de nuevo.'
const money = (value?: number) => typeof value === 'number' ? value.toLocaleString('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 }) : 'Consultar'

export default function CotizadorTraslados() {
  const apiUrl = import.meta.env.VITE_API_URL
  const base = `${apiUrl}/api/tarifas`
  const [origen, setOrigen] = useState<Seleccion>(null), [destino, setDestino] = useState<Seleccion>(null)
  const [origenTexto, setOrigenTexto] = useState(''), [destinoTexto, setDestinoTexto] = useState('')
  const [sugerencias, setSugerencias] = useState<Lugar[]>([]), [campoAbierto, setCampoAbierto] = useState<'origen' | 'destino' | null>(null)
  const [buscando, setBuscando] = useState(false), [cotizacion, setCotizacion] = useState<Cotizacion | null>(null), [cotizando, setCotizando] = useState(false)
  const [error, setError] = useState(''), [seccion, setSeccion] = useState<'cotizador' | 'tours' | 'extras'>('cotizador')
  const [tours, setTours] = useState<Tour[]>([]), [extras, setExtras] = useState<Extra[]>([]), [zonas, setZonas] = useState<Record<string, string>>({})
  const [datosError, setDatosError] = useState(''), [datosCargando, setDatosCargando] = useState(true), [cotizarIntento, setCotizarIntento] = useState(0), [buscarIntento, setBuscarIntento] = useState(0)
  const searchTimer = useRef<ReturnType<typeof setTimeout> | null>(null), haciaRef = useRef<HTMLInputElement>(null), resultadoRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const controller = new AbortController(); setDatosCargando(true)
    Promise.all([
      fetch(`${base}/tours`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error(); return r.json() }),
      fetch(`${base}/extras`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error(); return r.json() }),
      fetch(`${base}/zonas`, { signal: controller.signal }).then((r) => { if (!r.ok) throw new Error(); return r.json() }),
    ]).then(([toursData, extrasData, zonasData]) => { setTours(Array.isArray(toursData) ? toursData : []); setExtras(Array.isArray(extrasData) ? extrasData : []); setZonas(Object.fromEntries((Array.isArray(zonasData) ? zonasData : []).map((zona: Zona) => [zona.clave, zona.nombre]))); setDatosError('') })
      .catch((e: Error) => { if (e.name !== 'AbortError') setDatosError(networkMessage) }).finally(() => setDatosCargando(false))
    return () => controller.abort()
  }, [base])

  useEffect(() => {
    const texto = campoAbierto === 'origen' ? origenTexto : destinoTexto
    setSugerencias([])
    setBuscando(false)
    if (!campoAbierto || texto.trim().length < 2) return
    if (searchTimer.current) clearTimeout(searchTimer.current)
    const controller = new AbortController()
    searchTimer.current = setTimeout(() => { if (controller.signal.aborted) return; setBuscando(true); fetch(`${base}/hoteles/buscar?q=${encodeURIComponent(texto.trim())}`, { signal: controller.signal })
      .then((r) => { if (!r.ok) throw new Error(); return r.json() }).then((data: Lugar[]) => { if (!controller.signal.aborted) setSugerencias(Array.isArray(data) ? data : []) })
      .catch((e: Error) => { if (!controller.signal.aborted && e.name !== 'AbortError') setError(networkMessage) })
      .finally(() => { if (!controller.signal.aborted) setBuscando(false) }) }, 250)
    return () => { clearTimeout(searchTimer.current as ReturnType<typeof setTimeout>); controller.abort() }
  }, [base, buscarIntento, campoAbierto, destinoTexto, origenTexto])

  useEffect(() => {
    if (!origen || !destino) { setCotizacion(null); setCotizando(false); return }
    const controller = new AbortController(); setCotizando(true); setError('')
    fetch(`${base}/cotizar?origen=${encodeURIComponent(origen._id)}&destino=${encodeURIComponent(destino._id)}`, { signal: controller.signal })
      .then((r) => { if (!r.ok) throw new Error(); return r.json() }).then((data: Cotizacion) => setCotizacion(data))
      .catch((e: Error) => { if (e.name !== 'AbortError') { setCotizacion(null); setError(networkMessage) } }).finally(() => setCotizando(false))
    return () => controller.abort()
  }, [base, cotizarIntento, destino, origen])
  useEffect(() => { if (cotizacion && !cotizando) resultadoRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }, [cotizacion, cotizando])

  const elegir = (tipo: 'origen' | 'destino', lugar: Lugar) => { if (tipo === 'origen') { setOrigen(lugar); setOrigenTexto(lugar.nombre); setTimeout(() => haciaRef.current?.focus(), 0) } else { setDestino(lugar); setDestinoTexto(lugar.nombre) }; setCampoAbierto(null); setSugerencias([]); setError('') }
  const intercambiar = () => { setOrigen(destino); setDestino(origen); setOrigenTexto(destino?.nombre ?? ''); setDestinoTexto(origen?.nombre ?? '') }
  const contenidoVacio = useMemo(() => !origen || !destino, [destino, origen])
  return <main className="container mx-auto min-w-0 max-w-6xl px-3 pb-[calc(1rem+env(safe-area-inset-bottom))] pt-3 sm:px-4 sm:py-8">
    <div className="mb-4 min-w-0"><p className="text-sm font-medium text-indigo-600">Tarifas públicas</p><h1 className="mt-1 break-words text-2xl font-semibold text-gray-900 sm:text-3xl">Cotizador de traslados</h1><p className="mt-1 text-sm text-gray-500">Consulta rápida para compartir un precio claro con el pasajero.</p></div>
    <div className="mb-4 grid grid-cols-3 gap-1 rounded-xl border border-gray-200 bg-white/80 p-1 shadow-sm">{([['cotizador', 'Cotizar'], ['tours', 'Tours'], ['extras', 'Extras']] as const).map(([id, label]) => <button key={id} type="button" onClick={() => setSeccion(id)} aria-current={seccion === id ? 'page' : undefined} className={`min-h-11 rounded-lg px-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 ${seccion === id ? 'bg-indigo-600 text-white shadow-sm' : 'text-gray-600 hover:bg-gray-100'}`}>{label}</button>)}</div>
    {seccion === 'cotizador' && <section className="min-w-0 rounded-xl bg-white p-3 shadow-lg sm:p-6" aria-labelledby="cotizador-titulo"><h2 id="cotizador-titulo" className="sr-only">Origen y destino</h2><div className="grid min-w-0 gap-3 md:grid-cols-[1fr_auto_1fr] md:items-end"><LugarInput label="Desde" value={origenTexto} selected={origen} zonas={zonas} loading={buscando && campoAbierto === 'origen'} open={campoAbierto === 'origen'} suggestions={campoAbierto === 'origen' ? sugerencias : []} onFocus={() => setCampoAbierto('origen')} onChange={(value) => { setOrigenTexto(value); setOrigen(null); setError('') }} onSelect={(l) => elegir('origen', l)} /><button type="button" onClick={intercambiar} disabled={!origen && !destino} aria-label="Intercambiar origen y destino" className="mx-auto grid min-h-11 min-w-11 shrink-0 place-items-center rounded-full border border-gray-200 text-indigo-600 transition-colors hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 md:mb-0"><span aria-hidden className="text-xl">⇄</span></button><LugarInput inputRef={haciaRef} label="Hacia" value={destinoTexto} selected={destino} zonas={zonas} loading={buscando && campoAbierto === 'destino'} open={campoAbierto === 'destino'} suggestions={campoAbierto === 'destino' ? sugerencias : []} onFocus={() => setCampoAbierto('destino')} onChange={(value) => { setDestinoTexto(value); setDestino(null); setError('') }} onSelect={(l) => elegir('destino', l)} /></div>
      <div className="mt-4"><span className="mb-2 block text-xs font-medium text-gray-500">Accesos rápidos</span><div className="flex max-w-full flex-wrap gap-2">{QUICK_PLACES.map((place) => <button key={place._id} type="button" onClick={() => elegir('origen', place)} className="min-h-11 rounded-full border border-indigo-100 bg-indigo-50 px-3 text-xs font-medium text-indigo-700 hover:bg-indigo-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{place.nombre}</button>)}</div></div>
      {error && <div role="alert" className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-sm text-red-700"><span>{error}</span><button type="button" onClick={() => { setCotizarIntento((n) => n + 1); setBuscarIntento((n) => n + 1) }} className="min-h-11 rounded-md px-3 font-semibold text-red-800 underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">Reintentar</button></div>}{cotizando && <div className="mt-5 animate-pulse rounded-xl border border-gray-100 bg-gray-50 p-5" aria-label="Consultando tarifa"><div className="h-4 w-1/3 rounded bg-gray-200" /><div className="mt-3 h-9 w-2/3 rounded bg-gray-200" /></div>}{!cotizando && cotizacion && <div ref={resultadoRef}><Resultado cotizacion={cotizacion} zonas={zonas} /></div>}{!cotizando && contenidoVacio && <div className="mt-6 rounded-xl border border-dashed border-gray-200 bg-gray-50/70 px-4 py-8 text-center"><p className="font-medium text-gray-700">Elige origen y destino</p><p className="mt-1 text-sm text-gray-500">Escribe al menos dos letras para encontrar un hotel o aeropuerto.</p></div>}</section>}{seccion !== 'cotizador' && <DatosSecundarios tipo={seccion} tours={tours} extras={extras} error={datosError} loading={datosCargando} onRetry={() => window.location.reload()} />}
  </main>
}

function LugarInput({ inputRef, label, value, selected, zonas, suggestions, loading, open, onFocus, onChange, onSelect }: { inputRef?: RefObject<HTMLInputElement | null>; label: string; value: string; selected: Seleccion; zonas: Record<string, string>; suggestions: Lugar[]; loading: boolean; open: boolean; onFocus: () => void; onChange: (value: string) => void; onSelect: (lugar: Lugar) => void }) {
  const sinResultados = open && !loading && value.trim().length >= 2 && suggestions.length === 0
  return <div className="relative min-w-0"><label className="mb-1 block text-sm font-medium text-gray-700">{label}</label><div className="relative"><input ref={inputRef} value={value} onFocus={onFocus} onChange={(e) => onChange(e.target.value)} placeholder="Hotel, zona o aeropuerto" autoComplete="off" enterKeyHint="search" aria-expanded={open && (suggestions.length > 0 || sinResultados)} aria-label={label} className="block min-h-11 w-full min-w-0 rounded-lg border border-gray-200 px-3 pr-20 text-base shadow-sm outline-none placeholder:text-gray-400 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500" />{value && <button type="button" aria-label={`Limpiar ${label}`} onClick={() => onChange('')} className="absolute right-9 top-0 grid min-h-11 min-w-11 place-items-center text-xl text-gray-500 hover:text-gray-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">×</button>}{loading && <span className="absolute right-3 top-3 text-xs text-gray-400" aria-label="Buscando">…</span>}{!loading && selected && <span className="absolute right-3 top-3 text-indigo-600" aria-hidden>✓</span>}</div>{open && (suggestions.length > 0 || sinResultados) && <div className="absolute z-20 mt-1 max-h-72 w-full overflow-y-auto rounded-lg border border-gray-200 bg-white p-1 shadow-xl" role="listbox">{suggestions.length > 0 ? suggestions.map((lugar) => <button key={lugar._id} type="button" role="option" onMouseDown={(e) => e.preventDefault()} onClick={() => onSelect(lugar)} className="min-h-12 w-full min-w-0 rounded-md px-3 py-2 text-left hover:bg-indigo-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><span className="block truncate text-base font-medium text-gray-800">{lugar.nombre}</span><span className="block truncate text-sm text-gray-500">{zoneName(lugar.zona, zonas)}{lugar.ubicacion ? ` · ${lugar.ubicacion}` : ''}</span></button>) : <p role="status" className="px-3 py-4 text-sm text-gray-600">Sin resultados para «{value.trim()}». Prueba con otro nombre o una zona (ej. Playa centro).</p>}</div>}</div>
}
function zoneName(clave: string | undefined, zonas: Record<string, string>) { if (!clave) return 'zona no indicada'; return zonas[clave] || ({ aeropuerto_cun: 'Aeropuerto Cancún', aeropuerto_tqo: 'Aeropuerto Tulum', cancun_centro: 'Cancún Centro', playa_centro: 'Playa Centro', tulum_centro: 'Tulum Centro' }[clave] ?? clave) }
function formatVigencia(vigencia?: string) { if (!vigencia) return 'No indicada'; const date = new Date(`${vigencia}T12:00:00`); return Number.isNaN(date.getTime()) ? vigencia : `Tarifas vigentes desde el ${new Intl.DateTimeFormat('es-MX', { day: 'numeric', month: 'long', year: 'numeric' }).format(date)}` }

function Resultado({ cotizacion, zonas }: { cotizacion: Cotizacion; zonas: Record<string, string> }) {
  const [copiado, setCopiado] = useState(false), origen = cotizacion.detalleOrigen?.nombre || 'origen', destino = cotizacion.detalleDestino?.nombre || 'destino'
  if (!cotizacion.encontrado) return <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4" role="status"><p className="font-semibold text-amber-900">No tenemos tarifa de {origen} a {destino} en el tarifario. Consulta directamente.</p></div>
  const vigencia = cotizacion.vigencia ? new Intl.DateTimeFormat('es-MX', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${cotizacion.vigencia}T12:00:00`)).replace('.', '') : 'fecha no indicada'
  const shareText = `🚐 Traslado ${origen} → ${destino}\nVan: ${money(cotizacion.van)}\nSprinter/Suburban: ${money(cotizacion.sprinter)}\n+ ${money(cotizacion.cargos?.[0]?.monto)} recepción · Tarifas sin casetas\nVigentes desde ${vigencia}`
  const compartir = async () => { if (navigator.share) await navigator.share({ title: 'Cotización de traslado', text: shareText }); else window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`, '_blank', 'noopener,noreferrer') }
  const copiar = async () => { await navigator.clipboard?.writeText(shareText); setCopiado(true); setTimeout(() => setCopiado(false), 1800) }
  return <div className="mt-6 min-w-0 overflow-hidden rounded-xl border border-indigo-100 bg-indigo-50/60 p-4 sm:p-5"><div className="grid grid-cols-2 gap-2 sm:gap-3"><Price label="Van" value={cotizacion.van} /><Price label="Sprinter / Suburban" value={cotizacion.sprinter} /></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={compartir} className="min-h-11 flex-1 rounded-lg bg-green-600 px-3 text-sm font-semibold text-white hover:bg-green-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-500">Compartir por WhatsApp</button><button type="button" onClick={copiar} className="min-h-11 rounded-lg border border-indigo-200 bg-white px-4 text-sm font-semibold text-indigo-700 hover:bg-indigo-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{copiado ? 'Copiado' : 'Copiar'}</button></div><div className="mt-4 grid gap-2 border-t border-indigo-100 pt-4 text-sm text-gray-700 sm:grid-cols-2"><p><span className="font-medium">Desde:</span> {origen} <span className="text-gray-500">({zoneName(cotizacion.detalleOrigen?.zona, zonas)})</span></p><p><span className="font-medium">Hacia:</span> {destino} <span className="text-gray-500">({zoneName(cotizacion.detalleDestino?.zona, zonas)})</span></p></div>{!!cotizacion.cargos?.length && <div className="mt-4 border-t border-indigo-100 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Cargos adicionales</p>{cotizacion.cargos.map((cargo, i) => <div key={`${cargo.concepto}-${i}`} className="mt-1 flex justify-between gap-3 text-sm text-gray-700"><span className="break-words">{cargo.concepto}</span><span className="shrink-0 font-medium">+{money(cargo.monto)}</span></div>)}</div>}{!!cotizacion.notas?.length && <div className="mt-4 border-t border-indigo-100 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Notas</p><ul className="mt-1 list-inside list-disc text-sm text-gray-700">{cotizacion.notas.map((nota, i) => <li key={`${nota}-${i}`} className="break-words">{nota}</li>)}</ul></div>}<div className="mt-4 text-sm text-gray-600"><span>{formatVigencia(cotizacion.vigencia)}</span>{cotizacion.nombreTabla && <span className="ml-4">Tabla: {cotizacion.nombreTabla}</span>}</div></div>
}
function Price({ label, value }: { label: string; value?: number }) { return <div className="min-w-0 rounded-lg bg-white p-3 shadow-sm sm:p-4"><p className="truncate text-xs font-medium text-gray-500 sm:text-sm">{label}</p><p className="mt-1 truncate text-2xl font-bold text-indigo-700 sm:text-3xl">{money(value)}</p></div> }
function DatosSecundarios({ tipo, tours, extras, error, loading, onRetry }: { tipo: 'tours' | 'extras'; tours: Tour[]; extras: Extra[]; error: string; loading: boolean; onRetry: () => void }) { const sinDatos = tipo === 'tours' ? tours.length === 0 : extras.length === 0; return <section className="min-w-0 rounded-xl bg-white p-3 shadow-lg sm:p-6"><h2 className="text-xl font-semibold text-gray-900">{tipo === 'tours' ? 'Tours disponibles' : 'Extras disponibles'}</h2>{error && <div role="alert" className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button type="button" onClick={onRetry} className="min-h-11 px-2 font-semibold underline">Reintentar</button></div>}{loading && <div className="mt-5 animate-pulse space-y-3" aria-label="Cargando datos"><div className="h-12 rounded-lg bg-gray-100" /><div className="h-20 rounded-lg bg-gray-100" /></div>}{!loading && sinDatos && !error ? <p className="mt-5 rounded-lg border border-dashed border-gray-200 bg-gray-50 p-5 text-center text-sm text-gray-500">No hay {tipo} publicados por ahora.</p> : !loading && tipo === 'tours' ? <div className="mt-4 space-y-4">{tours.map((tour, i) => <div key={`${tour.salida}-${i}`} className="min-w-0 overflow-x-auto rounded-lg border border-gray-200"><p className="border-b border-gray-200 bg-gray-50 px-3 py-2 text-sm font-semibold text-gray-800">{tour.salida || 'Salida'}</p><table className="w-full text-left text-sm"><thead><tr className="text-xs uppercase tracking-wide text-gray-500"><th className="px-3 py-2">Servicio</th><th className="px-3 py-2">Van</th><th className="px-3 py-2">Sprinter</th></tr></thead><tbody>{tour.items?.map((item, j) => <tr key={`${item.nombre}-${j}`} className="border-t border-gray-100"><td className="max-w-[190px] break-words px-3 py-2 text-gray-700">{item.nombre}</td><td className="px-3 py-2 font-medium">{money(item.van)}</td><td className="px-3 py-2 font-medium">{money(item.sprinter)}</td></tr>)}</tbody></table></div>)}</div> : !loading ? <div className="mt-4 overflow-x-auto rounded-lg border border-gray-200"><table className="w-full text-left text-sm"><thead><tr className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><th className="px-3 py-2">Extra</th><th className="px-3 py-2">Van</th><th className="px-3 py-2">Sprinter</th></tr></thead><tbody>{extras.map((extra, i) => <tr key={`${extra.nombre}-${i}`} className="border-t border-gray-100"><td className="max-w-[210px] break-words px-3 py-2 text-gray-700">{extra.nombre}</td><td className="px-3 py-2 font-medium">{money(extra.van)}</td><td className="px-3 py-2 font-medium">{money(extra.sprinter)}</td></tr>)}</tbody></table></div> : null}</section> }
